routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'admin'], function () {
    Admin::routes();
    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
});

Route::get('/cache-clear', function (){
    Artisan::call('view:clear');
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('route:clear');
    return redirect()->back();
});

Route::get('/parents', [
    'uses' => 'AuthController@auth'
]);

Route::get('/save-shortcode', [
    'uses' => 'GlobalController@saveShortcodes'
]);

Route::get('/remove-shortcode', [
    'uses' => 'GlobalController@removeShortcodes'
]);

Route::get('/export-excel', [
    'uses' => 'GlobalController@export',
    'as' => 'export-excel'
]);

Route::get('/blog', [
    'as' => 'blog',
    'uses' => 'NewsController@blog'
]);

Route::get('/blog/{id}-{slug}', [
    'as' => 'one-blog',
    'uses' => 'NewsController@oneNews'
]);


Route::get('/news/{id}-{slug}', [
    'as' => 'one-news',
    'uses' => 'NewsController@oneNews'
]);



Route::get('/oauth/{driver}', 'AuthController@redirectToProvider');
Route::get('/oauth/{driver}/callback', 'AuthController@handleProviderCallback');

$pages = \App\Page::get()->pluck('slug')->toArray();




Route::get('/', [
    'as' => 'home',
    'uses' => 'HomeController@home'
]);

Route::get('/faq', [
    'as' => 'faq',
    'uses' => 'FaqController@faq'
]);

Route::get('/news', [
    'as' => 'news',
    'uses' => 'NewsController@news'
]);

Route::get('/liders', [
    'as' => 'liders',
    'uses' => 'LiderController@liders'
]);

Route::get('/show-liders', [
    'uses' => 'LiderController@showLiders'
]);



Route::get('/show-articles', [
    'uses' => 'NewsController@showArticles'
]);

Route::get('/setting', function () {
    return view('setting');
});

Route::get('/save-cookie', [
    'uses' => 'GlobalController@saveCookie'
]);

Route::get('/chat', function () {
    return view('chat');
});

Route::get('/account-liders', function () {
    return view('account-liders');
});

Route::get('/auth', [
    'as' => 'auth',
    'uses' => 'AuthController@auth'
]);

Route::post('/registration', [
    'as' => 'registration',
    'uses' => 'AuthController@registration'
]);

Route::post('/login', [
    'as' => 'login',
    'uses' => 'AuthController@login'
]);


Route::get('/counter-download-pdf', [
    'uses' => 'GlobalController@counterDownloadPdf'
]);

Route::get('/otg', [
    'uses' => 'OtgController@otg'
]);

Route::get('/show-otg', [
    'uses' => 'OtgController@showOtg'
]);

Route::get('/logout', [
    'as' => 'logout',
    'uses' => 'AuthController@logout'
]);

Route::group(['as' => 'account.', 'prefix' => 'account', 'middleware' => ['checkUser']], function() {

    Route::match(['get', 'post'], '/', [
        'as' => 'home',
        'uses' => 'AccountController@home'
    ]);

    Route::get('/instruction', [
        'as' => 'instruction',
        'uses' => 'AccountController@instruction'
    ]);

    Route::get('/liders', [
        'as' => 'liders',
        'uses' => 'AccountController@liders'
    ]);

    Route::get('/chat', [
        'as' => 'chat',
        'uses' => 'AccountController@chat'
    ]);

    Route::post('/save-message', [
        'as' => 'save-message',
        'uses' => 'AccountController@saveMessage'
    ]);

    Route::get('/save-current-area', [
        'uses' => 'AccountController@saveCurrentArea'
    ]);

    Route::get('/save-step-account', [
        'uses' => 'AccountController@saveStep'
    ]);

});

Route::get('/{page}', [
    'uses' => 'GlobalController@page'
])->where('slug', implode('|', $pages));

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use LaravelAdminPanel\Traits\Cropper;

class News extends Model
{
    use Cropper;

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function getCategoryAttribute($value) {
        $categorySlug = '';
        switch($this->category_id) {
            case 1:
                $categorySlug = 'news';
                break;
            case 2:
                $categorySlug = 'blog';
                break;
        }

        return $categorySlug;
    }

    public function save(array $options = []) {
        $tags = request()->tags;
        $this->tags()->sync($tags);


        parent::save();
    }
}

resources/views/blocks/list-articles.blade.php
@foreach($news as $new)
    <div class="col-lg-5 col-sm-6 @if($loop->iteration % 2 === 0) bounceInRight @else offset-lg-1 bounceInLeft @endif animated">
        <div class="wrap-img">
            <div class="string-bottom"></div>
            <a href="{{ route('one-'.$new->category, ['id' => $new->id, 'slug' => $new->slug]) }}">
                @if(strpos($new->image, 'wp-content') === false && strpos($new->image, 'post') === false && strpos($new->image, 'page') === false)
                    <img src="{{ $new->getCroppedPhoto('image', 'list', 'photo')}}" alt="">
                @else
                    <img style="height: 92%" src="{{ $new->image }}" alt="">
                @endif
            </a>
        </div>
        <div class="wrap-content">
            <a href="{{ route('one-'.$new->category, ['id' => $new->id, 'slug' => $new->slug]) }}" class="title">{{ $new->post_title }}</a>
            <span class="date">{{ getMonth($new->created_at) }} {{ date('d', strtotime($new->created_at)) }}, {{ date('Y', strtotime($new->created_at)) }}</span>
            <p>{{ $new->post_excerpt }}</p>
            <a href="{{ route('one-'.$new->category, ['id' => $new->id, 'slug' => $new->slug]) }}" class="btn-more">Читати</a>
        </div>
    </div>
@endforeach

resources/views/blocks/list-liders.blade.php
@foreach($liders as $lider)
    <li>
        <img src="{{ $lider->getCroppedPhoto('image', 'avatar', 'max') }}" alt="">
        <span class="name-lider">{{ $lider->name }}</span>
        <span class="area-lider">{{ $lider->regionId->region }}</span>

        <ul>
            <li><span>Телефон:</span> <a href="">{{ $lider->phone }}</a></li>
            <li><span>E-mail:</span> <a href="mailto:{{ $lider->email }}">{{ $lider->email }}</a></li>
        </ul>
    </li>
@endforeach

resources/views/blocks/list-news.blade.php
@foreach($news as $new)
    <li>
        <div class="wrap-news">
            <div class="news-img">
                <div class="string-right"></div>

                <a href="{{ route('one-'.$new->category, ['id' => $new->id, 'slug' => $new->slug]) }}">
                    @if(strpos($new->image, 'wp-content') === false && strpos($new->image, 'post') === false && strpos($new->image, 'page') === false)
                        <img src="{{ $new->getCroppedPhoto('image', 'list', 'photo')}}" alt="">
                    @else
                        <img style="height: 92%" src="{{ $new->image }}" alt="">
                    @endif
                </a>
            </div>
            <div class="content-news">
                <a class="name-news" href="{{ route('one-'.$new->category, ['id' => $new->id, 'slug' => $new->slug]) }}">{{ $new->post_title }}</a>
                <span>{{ getMonth($new->date_publication) }} {{ date('d', strtotime($new->date_publication)) }}, {{ date('Y', strtotime($new->date_publication)) }}</span>
                <p>{{ $new->post_excerpt }}</p>

                <a href="{{ route('one-'.$new->category, ['id' => $new->id, 'slug' => $new->slug]) }}" class="read-more">Читати</a>
            </div>
        </div>
    </li>
@endforeach

resources/views/blocks/list-otg.blade.php
@foreach($otgs as $otg)
    <li>
        <h4>{{ $otg->name }}</h4>
        <ul>
            <li><span>Індекс:</span> {{ $otg->index }}</li>
            <li><span>Область:</span> {{ $otg->regionId->region }}</li>
            <li><span>Район:</span> {{ $otg->area }}</li>
            <li><span>Село/Місто/Смт:</span> {{ $otg->city }}</li>
            <li><span>Вулиця:</span> {{ $otg->city }}</li>
            <li><span>Будинок:</span> {{ $otg->house }}</li>
            <li><span>E-mail:</span> {{ $otg->email }}</li>
            <li><span>Телефон:</span>{{ $otg->phone }}</li>
        </ul>
    </li>
@endforeach

resources/views/blocks/shortcode-admin.blade.php
<li data-id="{{ $shortCode->id }}" data-text="{{ $shortCode->text }}">
    <p style="width:49%;display: inline-block;"><input class="form-control quote-text" type="text" readonly="" value="{{ $shortCode->text }}"></p>
    <p style="width:49%;display: inline-block;"><input class="form-control" type="text" readonly="" value="{{ '[quote]'. $shortCode->id .'[/quote]' }}"></p>
    <ul style="list-style: none; padding-left: 0;">
        <li><a href="" class="btn btn-success hide">Зберігти</a></li>
        <li><a href="" class="btn-primary btn">Редагувати</a></li>
        <li><a href="" class="btn btn-danger">Видалити</a></li>
    </ul>
</li>

resources/views/blocks/sidebar.blade.php
<div class="col-lg-3 col-md-5">
    <div class="list-categories-news">
        <ul>
            <li><a href="{{ url('parents') }}">БАТЬКАМ</a></li>
            <li><a href="{{ url('enlighten') }}">ОСВІТЯНАМ</a></li>
            <li><a href="{{ url('cooks') }}">КУХАРЯМ</a></li>
        </ul>
    </div>

    <div class="siderbar-news">
        <h3>Новини Проекту</h3>
        <ul>
            @foreach($articles as $new)
                <li>
                    <ul>
                        <li>
                            <a href="{{ route('one-'.$new->category, ['id' => $new->id, 'slug' => $new->slug]) }}">
                                @if(strpos($new->image, 'wp-content') === false && strpos($new->image, 'post') === false && strpos($new->image, 'page') === false)
                                    <img src="{{ $new->getCroppedPhoto('image', 'photo', 'little')}}" alt="">
                                @else
                                    <img style="height: 92%" src="{{ $new->image }}" alt="">
                                @endif
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('one-'.$new->category, ['id' => $new->id, 'slug' => $new->slug]) }}">{{ $new->post_title }}</a>
                            <span>{{ getMonth($new->created_at) }} {{ date('d', strtotime($new->created_at)) }}, {{ date('Y', strtotime($new->created_at)) }}</span>
                        </li>
                    </ul>
                </li>
            @endforeach

        </ul>
    </div>

    <div class="help">
        <div class="overlay"></div>
        <span>Потрібна допомога?</span>
        <a href="{{ url('liders') }}">ЗВЕРНИСЬ ДО ЛІДЕРА</a>
    </div>

    <div class="socials">
        <h3>Ми в Соцмережах</h3>
        <img src="{{ asset('images/fb.jpg') }}" alt="">
    </div>
</div>